services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - backend

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    env_file:
      - .env
    ports:
      - "5000:5000"
